### PR TITLE
Extract underware shared

### PR DESCRIPTION
**Pull request by cschneid**
Extracted the shared profile definitions, and some of the constants that all were the same between files. The new file is Underware_Shared.scad, and I used `include` in each component to pull it in, which pulls in the variables and the function defs. 

I rendered each component after extracting the code to be sure I didn't break anything, but I'm not sure what a full test of things looks like. 

Also my editor apparently cares about trailing spaces so some of those changes came along too.

### CODE REVIEW

**Comment by AndyLevesque** [comment]
Greatly appreciate the support, but unable to merge at this time due to libraries not being supported by MakerWorld. Support by MakerWorld is an active requirement. There is a feature request out to MakerWorld to support custom libraries.

**Comment by ejwill** [comment]
fyi I am working on some code that leverages GitHub actions that will allow this to work on MakerWorld

**Comment by cschneid** [comment]
I'm going to close this. Annoying it won't work with MakerWorld. At least I got my dev environment for OpenSCAD setup now. 
@ejwill thanks for taking up the other approach with a build system to merge them.

**Comment by ejwill** [comment]
@cschneid I should have something ready this week so you will be able to re-open your PR when it is setup. I have it working in my fork tho I keep making improvements then breaking it 🤣

**Pull request closed without merging**
